### ISSUE TITLE
The game doesn't currently build for me

### ISSUE THREAD

**Issue by mleung** [0nix/Flixel-BeatEmUp#1]
Hi there, I'm getting errors in the FlxDebugger importing stuff when I try to build the current code:

```
import org.flixel.system.debug.Log;
import org.flixel.system.debug.Perf;
import org.flixel.system.debug.VCR;
import org.flixel.system.debug.Vis;
import org.flixel.system.debug.Watch;
```

This is just after I cloned the repo and tried to build it with FlashDevelop. Any insight would be great, thanks.

**Comment by 0nix** [comment]
I will look into this, please give me a day or two.

**Comment by mleung** [comment]
I got it working. No worries. Thanks.

**Comment by 0nix** [comment]
How did you get it to work?
